version: '3.9'
networks:
  mcqbot:
    driver: bridge
services:
  app:
    networks:
    - mcqbot
    build:
      context: .
      dockerfile: ./app.Dockerfile
    ports:
      - "80:80"
  graph:
    image: neo4j
    restart: unless-stopped
    networks:
    - mcqbot
    build: .
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}
    container_name: mcqbot-graph