version: '3.9'
networks:
  mcqbot:
    driver: bridge
    name: mcqbot
services:
  neo4j:
    networks:
      - mcqbot
    image: neo4j:latest
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      NEO4J_PLUGINS: '["graph-data-science"]'
    container_name: mcqbot-neo4j
    healthcheck:
          test: ["CMD", "neo4j", "status"]
          interval: 30s
          timeout: 10s
          retries: 5
  tests:
    networks:
      - mcqbot
    build:
      context: ..
      dockerfile: docker/tests.Dockerfile
    environment:
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      NEO4J_URI: ${NEO4J_URI}
    ports:
      - "5000:5000"
    command: sh -c 'poetry run pytest'
    depends_on:
      neo4j:
        condition: service_healthy
    image: tests:latest
    container_name: mcqbot-tests
  api:
    networks:
      - mcqbot
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    ports:
      - "80:80"
    image: api:latest
    container_name: mcqbot-api
    depends_on:
      neo4j:
        condition: service_healthy

    