name: Build/Run Docker Image on Merge
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}